---
bed_file: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/UCSC/hg19/Annotation/Genes/hg19_genes.bed
genome_lib_dir: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/STAR_Fusion/Hg19_CTAT_resource_lib
gtf_file: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes_with_ERCC.gtf
metasheet: metasheet.csv
picard_path: /zfs/cores/mbcf/mbcf-storage/devel/umv/software/picard-tools-1.115
python2: /apps/python-2.7.9/bin/python
ref_fasta: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome_with_ERCC.fa
reference: hg19
rseqc_path: /zfs/cores/mbcf/mbcf-storage/devel/umv/software/RSeQC/RSeQC-2.6.2/scripts
star_index: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/UCSC/hg19/Sequence/STARIndex_with_ERCC/
star_rRNA_index: /zfs/cores/mbcf/mbcf-storage/devel/umv/ref_files/human/Homo_sapiens/Ensembl/GRCh38/Sequences/non_coding_RNA/STAR_index/
## Is your library stranded? options are [True, False]
stranded: True
library_type: 'fr-firststrand'
varscan_jar_path: /home/lentaing/setup_files/varscan-master/VarScan.v2.4.1.jar
#file that is generated by gtf2annot.R--human and mouse annotations found in 
#static/ dir-- use bzip2 -d humanhg19.annot.csv.bz2
gene_annotation: viper/static/humanhg19.annot.csv



##PARAMS

## Sample-Sample Heatmap params
RPKM_threshold: 1.0
min_num_samples_expressing_at_threshold: 4

## Filters out "SNO" and "MIR" RNA, options are [True,False]
filter_mirna: True

## Number of genes to be represented in the Sample-Sample, Sample-Feature, and PCA plots
numgenes_plots: 1000

## Plotting param for Sample-Feature Heatmap. Number represents number of kmeans in heatmap, 0 will output a hierarchical clustering heatmap, finally, a list of numbers (0,2,4) will output all three heatmaps in the same pdf
num_kmeans_clust: 4

#Turn on the following if you want a genome wide snp scan in addition to chr6 scan
# possible value are [True,False]
snp_scan_genome: False

#Uncomment the following if you want to perform a scan of viral dna on your samples
# possible value are [True,False]
virus_dna_scan: False

# If this flag is on, you must have a metasheet column called batch with at least 2 samples per batch
## Options are [False, True]
batch_effect_removal: False

## adjpval for a gene to be considered differentially expressed and be included in GOterm analysis
goterm_adjpval_cutoff: 0.1
## Number of GOterms in plot
numgoterms: 5
## Number of KEGG pathways in plot (note there is no cutoff herre because the KEGG module takes in full population statistics)
numkeggpathways: 5

#Uncomment the following line to perform TIMER (immunology) analysis. refer to 
#README.md
#cancer_type: 'sarc'

#Uncomment the following line to perform a TRUST (cdr3) analysis.  refer to README.md
cdr3_analysis: False

the_samples:
  P4_OE1:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-1plus-DL2436_S4_R1_001.fastq.gz
  P4_OE2:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-2plus-DL2436_S5_R1_001.fastq.gz
  P4_OE3:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-3plus-DL2436_S6_R1_001.fastq.gz
  P4_WT1:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-1minus-DL2436_S1_R1_001.fastq.gz
  P4_WT2:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-2minus-DL2436_S2_R1_001.fastq.gz
  P4_WT3:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P4-3minus-DL2436_S3_R1_001.fastq.gz
  P7_OE1:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-1plus-DL2436_S10_R1_001.fastq.gz
  P7_OE2:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-2plus-DL2436_S11_R1_001.fastq.gz
  P7_OE3:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-3plus-DL2436_S12_R1_001.fastq.gz
  P7_WT1:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-1minus-DL2436_S7_R1_001.fastq.gz
  P7_WT2:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-2minus-DL2436_S8_R1_001.fastq.gz
  P7_WT3:
    - /zfs/cores/mbcf/mbcf-storage/devel/umv/snakemake/20151105-P7-3minus-DL2436_S9_R1_001.fastq.gz
