name: viper
channels: !!python/tuple
- anaconda
- bioconda
- conda-forge
- r
- ma-tongji
- defaults
dependencies:
- jpeg=8d=2
- libtiff=4.0.6=2
- pillow=3.4.2=py35_0
- bedtools=2.26.0=0
- bioconductor-annotate=1.50.0=0
- bioconductor-annotationdbi=1.32.3=0
- bioconductor-annotationforge=1.12.2=0
- bioconductor-biobase=2.32.0=0
- bioconductor-biocgenerics=0.18.0=r3.2.2_0
- bioconductor-biocparallel=1.4.3=r3.2.2_0
- bioconductor-biomart=2.28.0=r3.2.2_0
- bioconductor-biostrings=2.38.4=0
- bioconductor-category=2.36.0=r3.2.2_0
- bioconductor-clusterprofiler=3.0.4=1
- bioconductor-complexheatmap=1.6.0=1
- bioconductor-deseq2=1.10.1=r3.2.2_0
- bioconductor-do.db=2.9=0
- bioconductor-dose=2.10.6=0
- bioconductor-edger=3.14.0=0
- bioconductor-gage=2.21.1=0
- bioconductor-gagedata=2.8.0=0
- bioconductor-genefilter=1.52.1=r3.2.2_0
- bioconductor-geneplotter=1.48.0=0
- bioconductor-genomeinfodb=1.6.3=0
- bioconductor-genomicranges=1.22.4=0
- bioconductor-go.db=3.2.2=0
- bioconductor-gosemsim=1.28.2=0
- bioconductor-gostats=2.36.0=0
- bioconductor-graph=1.48.0=1
- bioconductor-gseabase=1.32.0=0
- bioconductor-iranges=2.4.8=0
- bioconductor-kegggraph=1.28.0=r3.2.2_0
- bioconductor-keggrest=1.10.1=r3.2.2_0
- bioconductor-limma=3.28.10=0
- bioconductor-multtest=2.26.0=0
- bioconductor-org.hs.eg.db=3.2.3=0
- bioconductor-org.mm.eg.db=3.2.3=0
- bioconductor-pathview=1.9.0=0
- bioconductor-qvalue=2.2.2=0
- bioconductor-rbgl=1.46.0=r3.2.2_1
- bioconductor-rgraphviz=2.14.0=0
- bioconductor-s4vectors=0.8.11=0
- bioconductor-summarizedexperiment=1.0.2=1
- bioconductor-sva=3.18.0=0
- bioconductor-topgo=2.22.0=0
- bioconductor-xvector=0.10.0=1
- bioconductor-zlibbioc=1.16.0=r3.2.2_1
- biopython=1.68=py35_0
- blast=2.6.0=boost1.60_0
- bowtie=1.2.0=py35_0
- cufflinks=2.2.1=py35_1
- curl=7.45.0
- dropbox=5.2.1=py35_0
- filechunkio=1.6=py35_0
- ftputil=3.2=py35_0
- gettext=0.19
- gmap=2016.09.23=1
- java-jdk=8.0.92=1
- libdb=6.1.26=0
- libxml2=2.9.3=0
- mmtf-python=1.0.5=py35_0
- perl-db-file=1.835=5
- perl-scalar-list-utils=1.45=2
- perl-set-intervaltree=0.10=3
- perl-threaded=5.22.0=10
- perl-uri=1.71=0
- picard=2.7.1=py35_0
- pysftp=0.2.8=py35_0
- python-dateutil=2.3=py35_0
- r-argparse=1.0.1=py35r3.2.2_0
- r-ash=1.0_15=r3.2.2_0
- r-bh=1.60.0_2=r3.2.2_0
- r-calibrate=1.7.2=r3.2.2_0
- r-catools=1.17.1=r3.2.2_0
- r-circlize=0.3.3=r3.2.2_0
- r-dendextend=1.1.2=r3.2.2_0
- r-digest=0.6.9=r3.2.2_0
- r-findpython=1.0.1=r3.2.2_0
- r-futile.logger=1.4.1=r3.2.2_0
- r-futile.options=1.0.0=r3.2.2_0
- r-getopt=1.20.0=r3.2.2_0
- r-getoptlong=0.1.0=r3.2.2_0
- r-ggalt=0.1.1=r3.2.2_0
- r-ggplot2=2.1.0=r3.2.2_0
- r-ggrepel=0.5=r3.2.2_0
- r-globaloptions=0.0.8=r3.2.2_0
- r-gsubfn=0.6_6=r3.2.2_0
- r-jsonlite=0.9.19=r3.2.2_0
- r-lambda.r=1.1.7=r3.2.2_0
- r-locfit=1.5_9.1=r3.2.2_0
- r-magrittr=1.5=r3.2.2_0
- r-mutoss=0.1_10=r3.2.2_0
- r-plotrix=3.6_1=r3.2.2_0
- r-png=0.1.7=r3.2.2_0
- r-proj4=1.0_8=r3.2.2_0
- r-shape=1.4.2=r3.2.2_0
- r-snow=0.4_1=r3.2.2_0
- r-viridis=0.3.1=r3.2.2_0
- samtools=1.3.1=5
- snakemake=3.9.1=py35_0
- snpeff=4.3=3
- star=2.5.2b=0
- star-fusion=0.5.4=2
- tbb=4.4_20150728=0
- ucsc-bedgraphtobigwig=332=0
- ucsc-bedsort=332=0
- ucsc-fetchchromsizes=332=0
- urllib3=1.12=py35_0
- varscan=2.4.2=0
- boost=1.60.0=py35_0
- cairo=1.12.18=6
- cffi=1.9.1=py35_0
- certifi=2016.2.28=py35_0
- gmp=6.1.0=0
- gsl=2.2.1=0
- libffi=3.2.1=1
- libiconv=1.14=0
- msgpack-python=0.4.8=py35_0
- ncurses=5.9=10
- pandas=0.19.2=np111py35_1
- pixman=0.32.6=0
- pyasn1=0.1.9=py35_0
- pycparser=2.17=py35_0
- pytz=2016.10=py35_0
- requests=2.12.4=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- wheel=0.29.0=py35_0
- wrapt=1.10.8=py35_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- cryptography=1.7.1=py35_0
- docutils=0.13.1=py35_0
- ecdsa=0.13=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.50.2=1
- harfbuzz=0.9.39=1
- icu=54.1=0
- idna=2.2=py35_0
- jbig=2.1=0
- libgcc=5.2.0=0
- libpng=1.6.27=0
- r-sqldf=0.4_10=r3.2.2_0
- mkl=2017.0.1=0
- mysql=5.5.24=0
- numpy=1.11.3=py35_0
- openjdk=8.17.0.3=1
- openssl=1.0.2j=0
- pango=1.39.0=0
- paramiko=2.0.2=py35_0
- pcre=8.39=1
- pip=9.0.1=py35_1
- proj4=4.9.2=0
- pycrypto=2.6.1=py35_4
- python=3.5.2=0
- pyyaml=3.12=py35_0
- r=3.2.2=0
- r-acepack=1.3_3.3=r3.2.2_1a
- r-assertthat=0.1=r3.2.2_1a
- r-base=3.2.2=0
- r-bitops=1.0_6=r3.2.2_1a
- r-boot=1.3_17=r3.2.2_0a
- r-brew=1.0_6=r3.2.2_1a
- r-chron=2.3_47=r3.2.2_0a
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-colorspace=1.2_6=r3.2.2_0a
- r-crayon=1.3.1=r3.2.2_0a
- r-curl=0.9.4=r3.2.2_0a
- r-dbi=0.3.1=r3.2.2_2a
- r-devtools=1.9.1=r3.2.2_0a
- r-dichromat=2.0_0=r3.2.2_2a
- r-doparallel=1.0.10=r3.2.2_0a
- r-dplyr=0.4.3=r3.2.2_0a
- r-evaluate=0.8=r3.2.2_0a
- r-foreach=1.4.3=r3.2.2_0a
- r-foreign=0.8_66=r3.2.2_0a
- r-formula=1.2_1=r3.2.2_0a
- r-gdata=2.17.0=r3.2.2_0a
- r-git2r=0.11.0=r3.2.2_0a
- r-gplots=2.17.0=r3.2.2_0a
- r-gridbase=0.4_7=r3.2.2_0a
- r-gridextra=2.0.0=r3.2.2_0a
- r-gtable=0.1.2=r3.2.2_2a
- r-gtools=3.5.0=r3.2.2_0a
- r-hmisc=3.17_0=r3.2.2_0a
- r-httr=1.0.0=r3.2.2_0a
- r-igraph=1.0.1=r3.2.2_0a
- r-irlba=2.0.0=r3.2.2_0a
- r-iterators=1.0.8=r3.2.2_0a
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-labeling=0.3=r3.2.2_1a
- r-lattice=0.20_33=r3.2.2_0a
- r-latticeextra=0.6_26=r3.2.2_2a
- r-lazyeval=0.1.10=r3.2.2_2a
- r-maps=3.0.0_2=r3.2.2_0a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-memoise=0.2.1=r3.2.2_1a
- r-mgcv=1.8_9=r3.2.2_0a
- r-mime=0.4=r3.2.2_0a
- r-multcomp=1.4_1=r3.2.2_0a
- r-munsell=0.4.2=r3.2.2_1a
- r-mvtnorm=1.0_3=r3.2.2_0a
- r-nlme=3.1_122=r3.2.2_0a
- r-nmf=0.20.6=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-pkgmaker=0.22=r3.2.2_0a
- r-plyr=1.8.3=r3.2.2_0a
- r-proto=0.3_10=r3.2.2_1a
- r-r6=2.1.1=r3.2.2_0a
- r-rcolorbrewer=1.1_2=r3.2.2_2a
- r-rcpp=0.12.2=r3.2.2_0a
- r-rcpparmadillo=0.6.200.2.0=r3.2.2_0a
- r-rcurl=1.95_4.7=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-registry=0.3=r3.2.2_0a
- r-reshape2=1.4.1=r3.2.2_1a
- r-rjson=0.2.15=r3.2.2_0a
- r-rngtools=1.2.4=r3.2.2_0a
- r-roxygen2=5.0.1=r3.2.2_0a
- r-rpart=4.1_10=r3.2.2_0a
- r-rsqlite=1.0.0=r3.2.2_1a
- r-rstudioapi=0.3.1=r3.2.2_0a
- r-rversions=1.0.2=r3.2.2_0a
- r-sandwich=2.3_4=r3.2.2_0a
- r-scales=0.3.0=r3.2.2_0a
- r-sparsem=1.7=r3.2.2_0a
- r-spatial=7.3_11=r3.2.2_0a
- r-stringi=1.0_1=r3.2.2_0a
- r-stringr=1.0.0=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-th.data=1.0_6=r3.2.2_1a
- r-tidyr=0.3.1=r3.2.2_0a
- r-whisker=0.3_2=r3.2.2_1a
- r-xml=3.98_1.3=r3.2.2_0a
- r-xml2=0.1.2=r3.2.2_0a
- r-xtable=1.8_0=r3.2.2_0a
- r-zoo=1.7_12=r3.2.2_1a
- readline=6.2=2
- reportlab=3.3.0=py35_0
- tk=8.5.18=0
- xz=5.2.2=1

