name: viper_py2
channels: !!python/tuple
- bioconda
- r
- defaults
dependencies:
- bcftools=1.3.1=1
- biopython=1.68
- bx-python=0.7.3
- curl=7.45.0
- htslib=1.3.2=0
- jpeg=9b=0
- mmtf-python=1.0.5
- pysam=0.8.3
- rseqc=2.6.2=0
- samtools=1.3.1=5
- cython=0.25.2=py27_0
- freetype=2.5.5
- jbig=2.1
- libgcc=5.2.0
- libpng=1.6.27
- libtiff=4.0.6
- mkl=11.3.3
- msgpack-python=0.4.8=py27_0
- numpy=1.11.2=py27_0
- openssl=1.0.2j
- pillow=4.0.0=py27_0
- pip=9.0.1=py27_1
- python=2.7.13
- readline=6.2
- reportlab=3.3.0=py27_0
- setuptools=27.2.0=py27_0
- sqlite=3.13.0
- system=5.8
- tk=8.5.18
- wheel=0.29.0=py27_0
- xz=5.2.2
- zlib=1.2.8
- pip:
  - distribute==0.6.10


