# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

#Metasheet with left or single mate, sample_name, condition1, condition2, ..., conditionN
#Right mate has to follow the same name convention as that of it's left mate, except for _R2_ . This will be _R1_ in left mate file name.
#Refer to https://github.com/vangalamaheshh/ROOT/blob/master/bioifx/pipelines/snakemake/metasheet.sample.csv
metasheet: metasheet.csv

#possible values are, true and false
stranded: true
# if stranded true, library_type is a required argument
# Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: fr-firststrand

# Tosh R code requires these params
#################
######PARAMS
##################
# Sample-Sample Heatmap params
RPKM_threshold: 2.0
min_num_samples_expressing_at_threshold: 4

SSnumgenes: 250
SFnumgenes: 1000

num_kmeans_clust: '0,4'

filter_mirna: "TRUE"

# Varscan - default turned off 
snp_scan_genome: "false"

# VirusSeq module - possible values [true,false]
virus_dna_scan: "false"

# Pathway params
numgoterms: 10
goterm_adjpval_cutoff: 0.05
kegg_pval_cutoff: 0.05
numkeggpathways: 5

# Batch params
batch_effect_removal: "false"

# sub-analyses
analysis_token: 
